# 1行あたりの文字数に制限を設けない
MD013: false

# 見出しのテキストの重複を許容する
MD024: false

# 順序付きリストのバリデーションは行わない
MD029: false

# 一部の HTML タグを許容する
MD033:
  allowed_elements:
    - br
    - u
    - b
    - table
    - thead
    - tbody
    - th
    - tr
    - td
    - p
    - blockquote
    - ul
    - li

# コードブロックに言語の指定は不要とする
MD040: false
